Repository EpiLink/EpiLink, pull requests merged in 2020-05, with the labels that each got.

#144 Fix license header and fix coroutine scopes' exception handling
  CHANGELOG.md
  LHEADER
  bot/build.gradle
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscord4JFacadeImpl.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkRoleManager.kt
  bot/src/main/kotlin/org/epilink/bot/ratelimiting/RateLimiter.kt
  web/build.gradle
Labels: Area: Back-end

#146 Add instance logo to front-end
  CHANGELOG.md
  web/src/App.vue
  web/src/store/index.js
  web/src/views/Home.vue
Labels: Area: Front-end

#142 Add a documentation website with Docsify
  .github/workflows/publishDocs.yaml
  CHANGELOG.md
  README.md
  docs/.nojekyll
  docs/Api.md
  docs/Developing.md
  docs/EpiLink.md
  docs/GDPR.md
  docs/MaintainerGuide.md
  docs/README.md
  docs/Rulebooks.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/bg.jpg
  docs/favicon.ico
  docs/index.html
  docs/logo.svg
Labels: Area: Documentation

#149 Added back button on meta text pages and fixed id accesses bugs
  CHANGELOG.md
  web/assets/back.svg
  web/src/store/accesses.js
  web/src/views/MetaText.vue
  web/src/views/Profile.vue
Labels: Area: Front-end, Status: READY

#148 Add contact information and "Instance" front-end page
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkBackEnd.kt
  bot/src/main/kotlin/org/epilink/bot/http/data/InstanceInformation.kt
  bot/src/test/kotlin/org/epilink/bot/BackEndTest.kt
  docs/Api.md
  docs/MaintainerGuide.md
  web/src/App.vue
  web/src/i18n/en.js
  web/src/i18n/fr.js
  web/src/router/routes.js
  web/src/views/Instance.vue
Labels: Area: Back-end, Area: Front-end

#150 Add an error for when frontendUrl does not have a trailing slash
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/test/kotlin/org/epilink/bot/ConfigTestCheck.kt
Labels: Area: Back-end

#151 Various doc enhancements and fixes
  docs/GDPR.md
  docs/MaintainerGuide.md
  docs/Rulebooks.md
Labels: Area: Documentation

#154 More small docs fixes
  CHANGELOG.md
  README.md
  docs/Developing.md
Labels: Area: Documentation

#155 Added back-end Docker support
  .gitignore
  CHANGELOG.md
  Dockerfile
  bot/docker_run.sh
  docs/MaintainerGuide.md
Labels: Area: Back-end, Status: READY
