Repository EpiLink/EpiLink, pull requests merged in 2020-04, with the labels that each got.

#110 Fixed frontend version
  web/package.json
Labels: Status: READY

#111 Add logo configuration on the back-end
  CHANGELOG.md
  bot/config/epilink_config.yaml
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkBackEnd.kt
  bot/src/test/kotlin/org/epilink/bot/BackEndTest.kt
  docs/MaintainerGuide.md
Labels: Area: Back-end

#115 Fixed CORS
  bot/src/main/kotlin/org/epilink/bot/http/LinkFrontEndHandler.kt
Labels: Area: Back-end, Status: READY, Type: Bug

#118 Fix build.gradle for bundling front-end
  CHANGELOG.md
  bot/build.gradle
Labels: Area: Back-end

#114 Fix rulebook location in docs
  bot/config/epilink_config.yaml
  docs/MaintainerGuide.md
Labels: Area: Documentation

#120 Remove HTTPS redirection on the back-end
  CHANGELOG.md
  bot/config/epilink_config.yaml
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkHttpServer.kt
  bot/src/test/kotlin/org/epilink/bot/TestUtils.kt
  docs/MaintainerGuide.md
Labels: Area: Back-end

#125 The 'remember me' checkbox is now checked when it should be
  CHANGELOG.md
  web/src/store/auth.js
Labels: Area: Front-end, Status: READY, Type: Bug

#127 Fix #121
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/http/LinkBackEnd.kt
  bot/src/test/kotlin/org/epilink/bot/BackEndTest.kt
Labels: Area: Back-end

#128 0.1.1 release
  CHANGELOG.md
  bot/build.gradle
  bot/config/epilink_config.yaml
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkBackEnd.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkFrontEndHandler.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkHttpServer.kt
  bot/src/test/kotlin/org/epilink/bot/BackEndTest.kt
  bot/src/test/kotlin/org/epilink/bot/TestUtils.kt
  docs/MaintainerGuide.md
  web/package-lock.json
  web/package.json
  web/src/store/auth.js
Labels: Area: Back-end, Area: Documentation, Area: Front-end

#132 Implement better getThing for generic maps and lists for rulebooks
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/config/rulebook/QuickHttp.kt
  bot/src/test/kotlin/org/epilink/bot/rulebooks/RulebookHelpersTest.kt
  docs/Rulebooks.md
Labels: Area: Back-end, Type: Enhancement

#134 Front-end improvements
  CHANGELOG.md
  web/public/favicon.ico
  web/src/App.vue
  web/src/i18n/en.js
  web/src/i18n/fr.js
  web/src/store/auth.js
  web/src/views/Profile.vue
Labels: Area: Front-end, Status: READY, Type: Enhancement

#136 Remove old information from the docs
  docs/MaintainerGuide.md
Labels: Area: Documentation

#135 Implement rule role caching
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/CacheClient.kt
  bot/src/main/kotlin/org/epilink/bot/LinkRedisClient.kt
  bot/src/main/kotlin/org/epilink/bot/LinkServerEnvironment.kt
  bot/src/main/kotlin/org/epilink/bot/Main.kt
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkServerDatabase.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscord4JFacadeImpl.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkRoleManager.kt
  bot/src/main/kotlin/org/epilink/bot/discord/RuleMediator.kt
  bot/src/main/kotlin/org/epilink/bot/discord/StandardRoles.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkBackEnd.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkRedisClient.kt
  bot/src/main/kotlin/org/epilink/bot/rulebook/Durations.kt
  bot/src/main/kotlin/org/epilink/bot/rulebook/QuickHttp.kt
  bot/src/main/kotlin/org/epilink/bot/rulebook/Rulebook.kt
  bot/src/main/kotlin/org/epilink/bot/rulebook/RulebookLoader.kt
  bot/src/test/kotlin/org/epilink/bot/BackEndTest.kt
  bot/src/test/kotlin/org/epilink/bot/DatabaseTest.kt
  bot/src/test/kotlin/org/epilink/bot/DiscordRoleManagerTest.kt
  bot/src/test/kotlin/org/epilink/bot/ModuleCheck.kt
  bot/src/test/kotlin/org/epilink/bot/rulebooks/RulebookDslTest.kt
  bot/src/test/kotlin/org/epilink/bot/rulebooks/RulebookHelpersTest.kt
  docs/GDPR.md
  docs/MaintainerGuide.md
  docs/Rulebooks.md
Labels: Area: Back-end, Type: Enhancement

#140 Reduce verbosity of the front-end handler in DEBUG
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/LogUtils.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkFrontEndHandler.kt
Labels: Area: Back-end
