Repository EpiLink/EpiLink, pull requests merged in 2020-06, with the labels that each got.

#165 Refactor more back-end things
  CHANGELOG.md
  bot/build.gradle
  bot/src/main/kotlin/org/epilink/bot/LinkServerEnvironment.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkDatabaseFacade.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkIdAccessor.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkIdManager.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkPermissionChecks.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkServerDatabase.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkUserCreator.kt
  bot/src/main/kotlin/org/epilink/bot/db/exposed/ExposedFacadeImpl.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkRoleManager.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkSessionChecks.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkAdminApi.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkRegistrationApi.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkUserApi.kt
  bot/src/test/kotlin/org/epilink/bot/AdminTest.kt
  bot/src/test/kotlin/org/epilink/bot/ApiUtils.kt
  bot/src/test/kotlin/org/epilink/bot/DatabaseTest.kt
  bot/src/test/kotlin/org/epilink/bot/DiscordRoleManagerTest.kt
  bot/src/test/kotlin/org/epilink/bot/IdAccessorTest.kt
  bot/src/test/kotlin/org/epilink/bot/PermissionChecksTest.kt
  bot/src/test/kotlin/org/epilink/bot/RegistrationTest.kt
  bot/src/test/kotlin/org/epilink/bot/SessionChecksTest.kt
  bot/src/test/kotlin/org/epilink/bot/TestUtils.kt
  bot/src/test/kotlin/org/epilink/bot/UserCreatorTest.kt
  bot/src/test/kotlin/org/epilink/bot/UserTest.kt
Labels: Area: Back-end

#168 Add notifications for bans
  CHANGELOG.md
  assets/ban256.png
  bot/config/epilink_config.yaml
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkBanManager.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscordMessages.kt
  bot/src/test/kotlin/org/epilink/bot/BanManagerTest.kt
  bot/src/test/kotlin/org/epilink/bot/MessagesTest.kt
  docs/MaintainerGuide.md
Labels: Area: Back-end

#172 Use ktor-rate-limit instead of the current code
  CHANGELOG.md
  bot/build.gradle
  bot/src/main/kotlin/org/epilink/bot/http/LinkBackEnd.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkMetaApi.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkRegistrationApi.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkUserApi.kt
  bot/src/main/kotlin/org/epilink/bot/ratelimiting/Rate.kt
  bot/src/main/kotlin/org/epilink/bot/ratelimiting/RateLimiter.kt
  bot/src/main/kotlin/org/epilink/bot/ratelimiting/RateLimiting.kt
  bot/src/main/kotlin/org/epilink/bot/ratelimiting/RateLimitingContext.kt
  bot/src/test/kotlin/org/epilink/bot/BackEndTest.kt
  bot/src/test/kotlin/org/epilink/bot/ratelimiting/RateLimitingTest.kt
  docs/MaintainerGuide.md
Labels: Area: Back-end

#173 Add GDPR report generator code and endpoint
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/LinkServerEnvironment.kt
  bot/src/main/kotlin/org/epilink/bot/LogUtils.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkGdprReport.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkIdManager.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkPermissionChecks.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkUserCreator.kt
  bot/src/main/kotlin/org/epilink/bot/db/Utils.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkSessionChecks.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkAdminApi.kt
  bot/src/test/kotlin/org/epilink/bot/AdminTest.kt
  docs/Api.md
  docs/MaintainerGuide.md
Labels: Area: Back-end, Type: Enhancement

#175 Allow using PDF in tos/policy
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/LinkLegalTexts.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkMetaApi.kt
  bot/src/test/kotlin/org/epilink/bot/LegalTextsTest.kt
  bot/src/test/kotlin/org/epilink/bot/MetaTest.kt
  docs/Api.md
  docs/MaintainerGuide.md
  web/src/api.js
  web/src/i18n/en.js
  web/src/i18n/fr.js
  web/src/store/texts.js
  web/src/views/MetaText.vue
Labels: Area: Back-end, Area: Front-end, Type: Enhancement

#180 Full frontend responsiveness
  CHANGELOG.md
  web/assets/menu.svg
  web/src/App.vue
  web/src/api.js
  web/src/components/Button.vue
  web/src/components/Check.vue
  web/src/components/Error.vue
  web/src/components/Option.vue
  web/src/components/Route.vue
  web/src/components/Stepper.vue
  web/src/components/User.vue
  web/src/i18n/en.js
  web/src/i18n/fr.js
  web/src/router/before.js
  web/src/styles/app.scss
  web/src/styles/mixins.scss
  web/src/styles/vars.scss
  web/src/views/About.vue
  web/src/views/Auth.vue
  web/src/views/Home.vue
  web/src/views/Instance.vue
  web/src/views/MetaText.vue
  web/src/views/Microsoft.vue
  web/src/views/NotFound.vue
  web/src/views/Profile.vue
  web/src/views/Redirect.vue
  web/src/views/Settings.vue
  web/src/views/Success.vue
Labels: Area: Front-end, Status: READY

#181 Change logo files with the new logo
  CHANGELOG.md
  assets/epilink1000.png
  assets/epilink256.png
  docs/logo.svg
  web/assets/logo.svg
Labels: Area: Back-end, Area: Documentation, Area: Front-end

#183 Fixed Docker image SSL + Netlify deployement
  Dockerfile
  bot/docker_run.sh
  web/package.json
Labels: Area: Back-end, Status: DRAFT

#191 Add the Interactive Rule Tester (IRT)
  CHANGELOG.md
  bot/src/main/kotlin/org/epilink/bot/InteractiveRuleTester.kt
  bot/src/main/kotlin/org/epilink/bot/Main.kt
  docs/IRT.md
  docs/Rulebooks.md
  docs/_sidebar.md
Labels: Area: Back-end

#178 Add Discord commands
  CHANGELOG.md
  bot/config/epilink_config.yaml
  bot/src/main/kotlin/org/epilink/bot/LinkLegalTexts.kt
  bot/src/main/kotlin/org/epilink/bot/LinkServerEnvironment.kt
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkBanLogic.kt
  bot/src/main/kotlin/org/epilink/bot/db/LinkPermissionChecks.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscord4JFacadeImpl.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscordClientFacade.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscordCommands.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscordMessages.kt
  bot/src/main/kotlin/org/epilink/bot/discord/LinkDiscordTargetResolver.kt
  bot/src/main/kotlin/org/epilink/bot/discord/cmd/HelpCommand.kt
  bot/src/main/kotlin/org/epilink/bot/discord/cmd/UpdateCommand.kt
  bot/src/main/kotlin/org/epilink/bot/http/LinkSessionChecks.kt
  bot/src/main/kotlin/org/epilink/bot/http/SimplifiedSessionStorage.kt
  bot/src/main/kotlin/org/epilink/bot/http/endpoints/LinkMetaApi.kt
  bot/src/test/kotlin/org/epilink/bot/DiscordTargetTest.kt
  bot/src/test/kotlin/org/epilink/bot/PermissionChecksTest.kt
  bot/src/test/kotlin/org/epilink/bot/SessionChecksTest.kt
  bot/src/test/kotlin/org/epilink/bot/commands/DiscordCommandsTest.kt
  bot/src/test/kotlin/org/epilink/bot/commands/HelpCommandTest.kt
  bot/src/test/kotlin/org/epilink/bot/commands/UpdateCommandTest.kt
  docs/DiscordCommands.md
  docs/_sidebar.md
Labels: Area: Back-end

#193 Move rulebook settings to general settings
  CHANGELOG.md
  bot/config/epilink_config.yaml
  bot/src/main/kotlin/org/epilink/bot/Main.kt
  bot/src/main/kotlin/org/epilink/bot/config/LinkConfig.kt
  docs/MaintainerGuide.md
Labels: Area: Back-end
