Repository EpiLink/EpiLink, pull requests merged in 2021-12, with the labels that each got.

#296 Add contributing note to website
  docs/EpiLink.md
  docs/_sidebar.md
Labels: Area: CII Best Practices

#292 Add Docker image job in GitHub Actions
  .dockerignore
  .gitattributes
  .github/workflows/backEndTests.yaml
  .github/workflows/publishDocs.yaml
  CHANGELOG.md
  Dockerfile
  bot/src/main/kotlin/org/epilink/bot/discord/Discord4JFacadeImpl.kt
  ci/publish-beta-site-to-gitlab.sh
  docker-compose.yaml
  docker/run.sh
  docs/src/Admin/Configuration.md
Labels: Area: Tests and CI

#319 0.7.0 beta 1 fixes
  .github/workflows/publishDocs.yaml
  CHANGELOG.md
  build.gradle
  docker-compose.yaml
  docs/src/Admin/Migration.md
  docs/src/_sidebar.md
Labels: Area: Documentation, Area: Tests and CI

#321 Fix #320
  bot/src/main/kotlin/org/epilink/bot/http/IdentityProvider.kt
Labels: Type: Bug, Area: Back-end

#323 Added .nvmrc file
  .nvmrc
  CHANGELOG.md
Labels: Area: Front-end
